version: '3.8'

services:
  web:
    build: ./src
    command: 'uvicorn core.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./src/:/usr/src/core/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://test:test@db/test
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test

volumes:
  postgres_data: